name: interview_coach
description: A Flutter app for Interview Coach
publish_to: 'none'
environment:
  sdk: "\>=2.18.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
flutter:
  uses-material-design: true
